{% set name = "DocBook XSL" %}
{% set tarname = name|lower|replace(' ', '-') %}
{% set version = "1.79.2" %}

package:
  name: {{ tarname }}
  version: {{ version }}

source:
  url: https://github.com/docbook/xslt10-stylesheets/releases/download/release/{{ version }}/{{ tarname }}-{{ version }}.tar.gz
  sha256: 966188d7c05fc76eaca115a55893e643dd01a3486f6368733c9ad974fcee7a26

build:
  noarch: generic
  number: 0

requirements:
  run:
    # xmlcatalog is required by post-link.{bat,sh} and
    # pre-unlink.{bat,sh}.
    - libxml2

test:
  requires:
    # Really need 2.10.3 build 6 or later.
    - libxml2

about:
  home: https://docbook.org
  license: X11
  license_file: COPYING
  summary: "XSL stylesheets for processing DocBook 5"
  description: |
    Modular, namespaced XSL stylesheets for transforming DocBook 5 XML
    to various output formats.
  dev_url: https://github.com/docbook/xslt10-stylesheets
  doc_url: https://tdg.docbook.org

extra:
  recipe-maintainers:
    - hattne
